project:
  type: website 
  output-dir: docs

website:
  navbar:
    background: 'transparent'
    search: true
    left:
      - text: "Maliny Po"
        href: index.qmd
      - text: "Industry"
        href: industry.qmd
      - text: "Personal"
        href: personal.qmd
      - text: "Contact"
        href: about.qmd

format:
  html:
    #theme: mint
    css: styles.css
    toc: false
    #include-before-body: gtm_code_body.html